version: '3.5'
services:

  dbsolicitacao:
    image: mysql
    container_name: dbsolicitacao
    hostname: dbsolicitacao
    restart: always
    networks:
      - net-driver
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solicitacaodb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536