services:
  
  # SERVICE DISCOVERY #
  eureka:
    extends:
      file: ./eureka/eureka.yml
      service: eureka

  # FRONT #
  front:
    extends:
      file: ./front/front.yml
      service: front
    links:
      - voluntario
      - solicitacaoong
    depends_on:
      - voluntario
      - solicitacaoong

  # SOLICITACAO SERVICO #
  solicitacaoong:
    extends:
      file: './solicitacaoong/solicitacao.yml'
      service: solicitacaoong
    links:
      - dbsolicitacao
    restart: on-failure
    depends_on:
      - eureka
      - dbsolicitacao
  dbsolicitacao:
    extends:
      file: './solicitacaoong/database.yml'
      service: dbsolicitacao
    restart: on-failure

  # VOLUNTARIO #
  voluntario:
    extends:
      file: ./voluntario/voluntario.yml
      service: voluntario
    links:
      - dbvoluntario
    restart: on-failure
    depends_on:
      - eureka
      - dbvoluntario
  dbvoluntario:
    extends:
      file: ./voluntario/database.yml
      service: dbvoluntario
    restart: on-failure

  # API-GATEWAY #
  apigateway:
    image: natasilva01/api-gateway
    container_name: api-gateway
    ports:
      - '9000:9000'
    networks:
      - net-driver

networks:
  net-driver:
    driver: bridge
